<a href="https://colab.research.google.com/github/ucmalik/PythonTestCodes/blob/master/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("hello world")

hello world


In [0]:
import numpy as np

In [0]:
a = np.array([[1, 2], [3, 1]])

In [0]:
print(a)

[[1 2]
 [3 1]]


In [0]:
np.transpose(a)

array([[1, 3],
       [2, 1]])

In [0]:
a

array([[1, 2],
       [3, 1]])

In [0]:
a(1)

TypeError: ignored

In [0]:
a[1]

array([3, 1])

In [0]:
 X = np.stack([np.ones(m), X], axis=1)
  theta=np.array([0.0, 0.0])
  theta  = np.transpose(theta)
    h = np.dot(theta,X[0,0:m-1])

IndentationError: ignored

In [0]:
m=5
X=np.array([1,1,1,0,0])
X = np.stack([np.ones(m), X], axis=1)
theta=np.array([1,1,1,0.0,0.0])
theta  = np.transpose(theta)
h = np.dot(theta,X[0:m,0])
print(h)

3.0


In [0]:
L = list(range(10))

In [0]:
print(range(12))

range(0, 12)


In [0]:
2**2

4

In [0]:
X = np.array([1,2,3,4]) 

In [0]:
print(X.size)

4


In [0]:
X[0:4]

array([1, 2, 3, 4])

In [0]:
np.amin(X)

1

In [0]:
np.amax(X)

4

In [0]:
 np.mean(X)

2.5

In [0]:
np.std(X)

1.118033988749895

In [0]:
X[:]

array([1, 2, 3, 4])

In [0]:
X[:] - 1

array([0, 1, 2, 3])

In [0]:
X[:] = X[:]+1

In [0]:
print(np.std(a[:,0]))

1.0


In [0]:
print(np.std(a[:,1]))

0.5


In [0]:
s = np.zeros(a.shape[1])

In [0]:
print(s)

[0. 0.]


In [0]:
s[0]

0.0

In [0]:
s[2]

IndexError: ignored

In [0]:
a = np.array([[1,2,3,4,4],[1,2,3,4,5],[1,2,2,2,1]])

In [0]:
a.shape[1]

5

In [0]:
s = np.zeros(a.shape[1])

In [0]:
print(s)

[0. 0. 0. 0. 0.]


In [0]:
s[2]

0.0

In [0]:
s[3]

0.0

In [0]:
s.size

5

In [0]:
sum(a[0,:]+1) #row zero sum it

19

In [0]:
c = 1

In [0]:
c = 1
d = 1
d/=2
print(d)
c/=2.0
print(c)

SyntaxError: ignored

In [0]:
c = 1
c++

SyntaxError: ignored

In [0]:
X[:0]

array([], dtype=int64)

In [0]:
X[:]

array([2, 3, 4, 5])

In [0]:
a[:,0]

array([1, 1, 1])

In [0]:
a[:,0].size

3

In [0]:
temp = np.ones((a[:,0].size,a.shape[1]+1))
temp[:,1:(a.shape[1]+1)] = a
temp[:,:]

array([[1., 1., 2., 3., 4., 4.],
       [1., 1., 2., 3., 4., 5.],
       [1., 1., 2., 2., 2., 1.]])

In [0]:
   X = np.array([[2104,3,399900],
    [1600,3,329900],
    [2400,3,369000],
    [1416,2,232000],
    [3000,4,539900],
    [1985,4,299900],
    [1534,3,314900],
    [1427,3,198999],
    [1380,3,212000],
    [1494,3,242500]])

In [0]:
X = np.concatenate([np.ones((X.shape[0], 1)), X], axis=1)

In [0]:
X.shape[0]

10

In [0]:
X

array([[1.00000e+00, 2.10400e+03, 3.00000e+00, 3.99900e+05],
       [1.00000e+00, 1.60000e+03, 3.00000e+00, 3.29900e+05],
       [1.00000e+00, 2.40000e+03, 3.00000e+00, 3.69000e+05],
       [1.00000e+00, 1.41600e+03, 2.00000e+00, 2.32000e+05],
       [1.00000e+00, 3.00000e+03, 4.00000e+00, 5.39900e+05],
       [1.00000e+00, 1.98500e+03, 4.00000e+00, 2.99900e+05],
       [1.00000e+00, 1.53400e+03, 3.00000e+00, 3.14900e+05],
       [1.00000e+00, 1.42700e+03, 3.00000e+00, 1.98999e+05],
       [1.00000e+00, 1.38000e+03, 3.00000e+00, 2.12000e+05],
       [1.00000e+00, 1.49400e+03, 3.00000e+00, 2.42500e+05]])

In [0]:
sigma = np.zeros(X.shape[1])
mu = np.zeros(X.shape[1])

sigma[[range(X.shape[1])] = np.std(X[:,[range(X.shape[1])]])
mu[range(X.shape[1])] = np.mean(X[:, range(X.shape[1])])

for i in range(1,X.shape[1]):
        X[:,i] = (X[:,i] - mu[i])/sigma[i]

SyntaxError: ignored

In [0]:
X

array([[ 1.        , -0.53224604, -0.54680079,  2.2235    ],
       [ 1.        , -0.53573752, -0.54680079,  1.73857249],
       [ 1.        , -0.53019549, -0.54680079,  2.00943914],
       [ 1.        , -0.53701219, -0.54680772,  1.06036674],
       [ 1.        , -0.52603897, -0.54679387,  3.19335502],
       [ 1.        , -0.53307042, -0.54679387,  1.53074642],
       [ 1.        , -0.53619474, -0.54680079,  1.63465946],
       [ 1.        , -0.53693598, -0.54680079,  0.83175113],
       [ 1.        , -0.53726158, -0.54680079,  0.92181602],
       [ 1.        , -0.53647184, -0.54680079,  1.13310586]])

In [0]:
np.mean([1,1])

1.0

In [0]:
sigma = np.zeros(X.shape[1])

In [0]:
sigma

array([0., 0., 0., 0.])

In [0]:
range(X.shape[1])

range(0, 4)

In [0]:
sigma[0]=1
sigma[0] = np.std(X[:,range(2)])

In [0]:
sigma

array([984.42630501,   0.        ,   0.        ,   0.        ])

In [0]:
sigma[0] = np.mean(X[:,[0,1]])
sigma
sigma[1] = np.mean(X[:,1])
sigma

array([ 917.5, 1834. ,    0. ,    0. ])

In [0]:
2104+1600+2400+1416+3000+1985+1534+1427+1380+1494

18340

In [0]:
(1+1+1+1+1+1+1+1+1+1+2104+1600+2400+1416+3000+1985+1534+1427+1380+1494)/20

917.5